config/routes.rb
Rails.application.routes.draw do
  root 'main#index' 
  post 'login' => 'main#login' , as: :login
  get '/add_to_cart/:id' => 'main#add_to_cart', as: :add_to_cart
  get '/sort_price' => 'main#sort_price' ,as: :sort_price
  get '/:div(.:format)' => 'main#index' ,as: :app

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def setupPageTab(params)
		@page_js='main/js/products.js.erb'

		if params[:div]=='cart'
			@page_js='main/js/cart.js.erb'

		elsif params[:div]=='success'
			@page_js='main/js/success.js.erb'

		end
	end

	def index
		setupPageTab params
		@data = File.read("#{Rails.root}/public/categories.json")
		@data = JSON.parse @data
	end

	def login
		puts params
		@login = File.read("#{Rails.root}/public/credential.json")
		@login = JSON.parse @login
		flag = 0
		@login["credentials"].each do |t|
			if t["username"] == params[:username]
				puts "in user"
				puts "#{t["username"]}"
				if t["password"] == params[:password]
					puts "in psw"
					puts "#{t["password"]}"
					flag = 1
					break
				end
			end
		end	
		cookies.delete :products
		if flag
			redirect_to app_path(div: 'success')
		else
			redirect_to app_path(div: 'cart')
		end
	end

	def add_to_cart
		puts params
		@products = cookies[:products]
		if @products.blank?
			@products = cookies[:products] = params[:id]
		else
			cookies[:products] = @products + ',' + params[:id]
		end
		respond_to do |format|
			puts "Respond to AJAX"
			format.js { render :template=>'main/js/additem.js.erb' }
		end
	end

	def sort_price
		puts params
		@data = File.read("#{Rails.root}/public/categories.json")
		@data = JSON.parse @data
		 @data.keys.each do |key|
		 	@data[key].sort_by!{ |hash| hash['price'] }
		 end

		  render 'main/index'
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
	def search_item(data,id)
		data.keys.each do |a|
			data[a].each do |c|
				if c["id"].to_s == id
					return c;
				end 
			end
		end 
	end

end

app/views/layouts/_footer.html.erb
<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "E-Commerce App" , root_path ,class: "navbar-brand"%>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<%= link_to app_path(div: 'cart') do %>
							<span class="glyphicon glyphicon-shopping-cart"></span> Cart
						<% end %>
					</li>
					<li>
						<a href="#">Services</a>
					</li>
					<li>
						<a href="#">Contact</a>
					</li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>E-Commerce</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/main/_cart.html.erb
<style type="text/css">
	#loginModal {
		top:5%;
		left:30%;
		outline: none;
	}

	#loginModal .modal-dialog  {width:75%;}
</style>
<h1>Shopping Cart</h1>
<%# cookies.delete :products%>
<% if !cookies[:products].blank? %>
	<% items = cookies[:products].split(',') %>
	<div class="shopping-cart">
		<div class="column-labels">
			<label class="product-image">Image</label>
			<label class="product-details">Product</label>
			<label class="product-price">Price</label>
			<label class="product-quantity">Quantity</label>
			<label class="product-removal">Remove</label>
			<label class="product-line-price">Total</label>
		</div>
		<% items.each do |item| %>
			<% item=search_item(@data,item) %>
			<div class="product">
				<div class="product-image">
					<img src=<%= item["img"] %> >
				</div>
				<div class="product-details">
					<div class="product-title"><%= item["name"] %></div>
					<p class="product-description"><%= item["desc"] %>.</p>
				</div>
				<div class="product-price"><%= item["price"] %></div>
				<div class="product-quantity">
					<input type="number" value="1" min="1">
				</div>
				<div class="product-removal">
					<button class="btn btn-danger">
						Remove
					</button>
				</div>
				<div class="product-line-price"><%= item["price"] %></div>
			</div>
		<% end %>

		<div class="totals">
			<div class="totals-item">
				<label>Subtotal</label>
				<div class="totals-value" id="cart-subtotal">71.97</div>
			</div>
			<div class="totals-item">
				<label>Tax (5%)</label>
				<div class="totals-value" id="cart-tax">3.60</div>
			</div>
			<div class="totals-item">
				<label>Shipping</label>
				<div class="totals-value" id="cart-shipping">15.00</div>
			</div>
			<div class="totals-item totals-item-total">
				<label>Grand Total</label>
				<div class="totals-value" id="cart-total">90.57</div>
			</div>
		</div>
		<%= link_to "Checkout" ,'#' ,class: "btn btn-info btn-lg pull-right",'data-toggle'=> "modal" ,'data-target'=>"#loginModal"%>

	</div>
<% end %>	

<!-- Modal -->
<div id="loginModal" class="modal fade" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Login</h4>
			</div>
			<div class="modal-body">
				<%= form_tag login_path,class: 'form-inline' do %>
					<div class="form-group">
	      		<%=label_tag 'username' %>
						<%= text_field_tag 'username' %>
	    		</div>
	    		<div class="form-group">
	      		<%=label_tag 'password' %>
						<%=password_field_tag 'password'%>
	    		</div>
					<%= submit_tag 'Complete Order',class: 'btn btn-info' %>
				</div>
			<% end %>
			</div>
		</div>

	</div>
</div>

app/views/main/_products.html.erb
<div class="container">

    <div class="row">

        <div class="col-md-3">
            <p class="lead">E-Commerce App</p>
            <div class="list-group">
                <% @data.keys.each do |category|%>
                    <%= link_to "#{category}",'#',class: "list-group-item",:onclick => 'func(this.text)' %>
                <% end %>
            </div>
            <p>Filters</p>
            <div class="checkbox">
                <%= link_to 'Sort by Price',sort_price_path,class: 'btn btn-default' %>
            </div>
        </div>

        <div class="col-md-9">
            <div class="alert alert-success hidden" id='cart_success'>
              <strong>Success!</strong> Item Succesfully added to cart
            </div>
            <div class="row carousel-holder">

                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="slide-image" src="http://g-ecx.images-amazon.com/images/G/31/img16/Grocery/SaleEvent/Ingress/hero_4500x900._UX1500_SX1500_CB270041112_.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://g-ecx.images-amazon.com/images/G/31/img16/PC/June/Storage/7984_Storageday_4500x900_without-logo._UX1500_SX1500_CB270023916_.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://g-ecx.images-amazon.com/images/G/31/img16/TV/Nobel/Monsoon/PC_GWbunk_4500x900_NobleMonsoonOffers._UX1500_SX1500_CB270227126_.jpg" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>

            </div>
            <% @data.keys.each do |category|%>
                <div class="row items" id=<%= category %> >
                <% @data[category].each do |item| %>
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src=<%= item["img"] %> alt="">
                            <div class="caption">
                                <h4 class="pull-right">Rs. <%= item["price"] %></h4>
                                <h4><a href="#"><%= item["name"] %></a>
                                </h4>
                                <p><%= item["desc"]%>.</p>
                            </div>
                            <div class="cart-div">
                                <p class="pull-right">
                                    <div><%= link_to "Add to cart",add_to_cart_path(item["id"]),:remote => true,class: 'btn btn-primary pull-left' %></div>
                                    <div><%= link_to "Buy Now",app_path(div: 'cart'),class: 'btn btn-success' %></div>
                                
                                </p>
                                    
                                
                            </div>
                        </div>
                    </div> 
                    <% end %>
                </div>
            <% end %>    
        </div>

    </div>

</div>

<script type="text/javascript">
    $('.items').addClass('hidden');
    a='<%= @data.keys[0] %>'
    $('#'+ a).removeClass('hidden');
    function func(text) {
        id = text
        $('.items').addClass('hidden');
        $('#'+id).removeClass('hidden');
              
    }   

</script>

app/views/main/_success.html.erb
<div class="container">
	<h1>Success</h1>
</div>

app/views/main/index.html.erb
<div id="products" class="ecom-div show">
	<%= render 'products' %>	
</div>

<div id="cart" class="ecom-div hidden">
	<%= render 'cart' %>	
</div>

<div id="success" class="ecom-div hidden">
	<%= render 'success' %>	
</div>

<script>
	<%if !@page_js.nil?%>
		<%=render :template=>@page_js %>
	<% end %>
</script>

app/views/main/js/additem.js.erb
$('#cart_success').removeClass('hidden')
window.setTimeout(function() {
      $('#cart_success').addClass('hidden')
}, 5000);

app/views/main/js/cart.js.erb
<%=render :template=>'main/js/divfix.js.erb'%>
$('#cart').removeClass('hidden');

/* Set rates + misc */
var taxRate = 0.05;
var shippingRate = 15.00; 
var fadeTime = 300;


/* Assign actions */
$('.product-quantity input').change( function() {
  updateQuantity(this);
});

$('.product-removal button').click( function() {
  removeItem(this);
});

recalculateCart();
/* Recalculate cart */
function recalculateCart()
{
  var subtotal = 0;
  
  /* Sum up row totals */
  $('.product').each(function () {
    subtotal += parseFloat($(this).children('.product-line-price').text());
  });
  
  /* Calculate totals */
  var tax = subtotal * taxRate;
  var shipping = (subtotal > 0 ? shippingRate : 0);
  var total = subtotal + tax + shipping;
  
  /* Update totals display */
  $('.totals-value').fadeOut(fadeTime, function() {
    $('#cart-subtotal').html(subtotal.toFixed(2));
    $('#cart-tax').html(tax.toFixed(2));
    $('#cart-shipping').html(shipping.toFixed(2));
    $('#cart-total').html(total.toFixed(2));
    if(total == 0){
      $('.checkout').fadeOut(fadeTime);
    }else{
      $('.checkout').fadeIn(fadeTime);
    }
    $('.totals-value').fadeIn(fadeTime);
  });
}


/* Update quantity */
function updateQuantity(quantityInput)
{
  /* Calculate line price */
  var productRow = $(quantityInput).parent().parent();
  var price = parseFloat(productRow.children('.product-price').text());
  var quantity = $(quantityInput).val();
  var linePrice = price * quantity;
  
  /* Update line price display and recalc cart totals */
  productRow.children('.product-line-price').each(function () {
    $(this).fadeOut(fadeTime, function() {
      $(this).text(linePrice.toFixed(2));
      recalculateCart();
      $(this).fadeIn(fadeTime);
    });
  });  
}


/* Remove item from cart */
function removeItem(removeButton)
{
  /* Remove row from DOM and recalc cart total */
  var productRow = $(removeButton).parent().parent();
  productRow.slideUp(fadeTime, function() {
    productRow.remove();
    recalculateCart();
  });
}

app/views/main/js/divfix.js.erb
$('.ecom-div').addClass('hidden');

app/views/main/js/products.js.erb
<%=render :template=>'main/js/divfix.js.erb'%>
$('#products').removeClass('hidden');

app/views/main/js/success.js.erb
<%=render :template=>'main/js/divfix.js.erb'%>
$('#success').removeClass('hidden');